#!/usr/bin/env node
// Generates every reference page of the Horizon docs site from one pinned commit.
//
//   node scripts/generate.mjs <commit-sha>
//
// Reads: the repo at <sha> (git show, never the working tree), sources/board.json,
// sources/figma.json, the deployed Storybook's index.json and the npm registry.
// Writes (overwriting): the home page, All components, one page per component,
// Tokens, Changelog, Roadmap, News, src/styles/horizon-tokens.css and the
// generated block of the sidebar in astro.config.mjs. Guides are never touched.
//
// Nothing here invents content: a section with no source gets a notice naming
// exactly what is missing.

import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');
const DOCS = path.join(ROOT, 'src/content/docs');

function die(msg) {
	console.error(`generate: ${msg}`);
	process.exit(1);
}

const shaArg = process.argv[2];
if (!shaArg) die('usage: node scripts/generate.mjs <commit-sha>');

// Run git from the repository root so pathspecs (src/..., package.json) mean the same thing everywhere.
const TOP = execFileSync('git', ['rev-parse', '--show-toplevel'], { cwd: ROOT, encoding: 'utf8' }).trim();
const git = (...args) => execFileSync('git', args, { cwd: TOP, encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 });
const SHA = git('rev-parse', '--verify', `${shaArg}^{commit}`).trim();
const SHORT = SHA.slice(0, 7);
const show = (p, rev = SHA) => git('show', `${rev}:${p}`);
const has = (p, rev = SHA) => {
	try {
		git('cat-file', '-e', `${rev}:${p}`);
		return true;
	} catch {
		return false;
	}
};

const readJson = (p) => JSON.parse(fs.readFileSync(path.join(ROOT, p), 'utf8'));
const cfg = readJson('reference.config.json');
const boardRaw = fs.readFileSync(path.join(ROOT, 'sources/board.json'), 'utf8');
if (/\brec[A-Za-z0-9]{14}\b/.test(boardRaw)) die('sources/board.json contains a registry record ID. Remove it.');
const board = JSON.parse(boardRaw);
const figma = readJson('sources/figma.json');

// ---------- helpers ----------

// Escape text for MDX prose and table cells.
const t = (s) =>
	String(s)
		.replace(/&/g, '&amp;')
		.replace(/</g, '&lt;')
		.replace(/>/g, '&gt;')
		.replace(/\{/g, '&#123;')
		.replace(/\}/g, '&#125;')
		.replace(/\|/g, '\\|');
// Inline code, safe in tables.
const c = (s) => '`' + String(s).replace(/\|/g, '\\|') + '`';
const attr = (s) => String(s).replace(/&/g, '&amp;').replace(/"/g, '&quot;');
const notice = (s) => `<p class="hz-missing"><strong>Missing source.</strong> ${t(s)}</p>`;
const blob = (p, line) => `${cfg.repoUrl}/blob/${SHA}/${p}${line ? `#L${line}` : ''}`;
const tree = (p) => `${cfg.repoUrl}/tree/${SHA}/${p}`;
const commitUrl = (h) => `${cfg.repoUrl}/commit/${h}`;
const GEN = `{/* Generated by docs-site/scripts/generate.mjs from ${SHA}. Don't edit by hand: change the source or the script. */}`;

function write(rel, content) {
	const file = path.join(DOCS, rel);
	fs.mkdirSync(path.dirname(file), { recursive: true });
	fs.writeFileSync(file, content.replace(/\n{3,}/g, '\n\n').trimEnd() + '\n');
	written.push(rel);
}
const written = [];

function frontmatter(obj) {
	const lines = ['---'];
	for (const [k, v] of Object.entries(obj)) {
		if (typeof v === 'string') lines.push(`${k}: ${JSON.stringify(v)}`);
		else lines.push(`${k}:\n${v.map((x) => '  ' + x).join('\n')}`);
	}
	lines.push('---');
	return lines.join('\n');
}

async function getJson(url) {
	const res = await fetch(url);
	if (res.status === 404) return null;
	if (!res.ok) die(`${url} answered ${res.status}`);
	return res.json();
}

// ---------- the repo at SHA ----------

const pkg = JSON.parse(show('package.json'));
const readme = has('README.md') ? show('README.md') : null;
const versioning = has('VERSIONING.md') ? show('VERSIONING.md') : null;
const decisions = has('decisions.md') ? show('decisions.md') : null;
const indexTs = show('src/index.ts');

function readmeFirstParagraph() {
	if (!readme) return null;
	const body = readme.replace(/^#[^\n]*\n/, '').trim();
	return body.split(/\n\s*\n/)[0].trim();
}
function readmeSection(title) {
	if (!readme) return null;
	const m = readme.match(new RegExp(`^## ${title}\\n([\\s\\S]*?)(?=^## |$(?![\\s\\S]))`, 'm'));
	return m ? m[1].trim() : null;
}
function mdSection(src, heading) {
	if (!src) return null;
	const lines = src.split('\n');
	const i = lines.findIndex((l) => l.trim() === heading);
	if (i < 0) return null;
	const level = heading.match(/^#+/)[0].length;
	const out = [];
	for (const l of lines.slice(i + 1)) {
		const h = l.match(/^(#+) /);
		if (h && h[1].length <= level) break;
		out.push(l);
	}
	return out.join('\n').trim();
}

// Tags reachable from SHA, oldest first.
const tags = git('tag', '--merged', SHA, '--sort=creatordate').split('\n').filter(Boolean);
const isAncestor = (a, b) => {
	try {
		git('merge-base', '--is-ancestor', a, b);
		return true;
	} catch {
		return false;
	}
};
const versionOf = (commit) => {
	for (const tag of tags) if (isAncestor(commit, tag)) return tag.replace(/^v/, '');
	return null;
};

// ---------- npm ----------

const npm = await getJson(`${cfg.npmRegistry}/${pkg.name.replace('/', '%2F')}`);
const published = npm
	? Object.keys(npm.versions || {})
			.map((v) => ({ version: v, time: npm.time?.[v] ?? null, meta: npm.versions[v] }))
			.sort((a, b) => (a.time < b.time ? -1 : 1))
	: [];
const latest = npm?.['dist-tags']?.latest ? published.find((p) => p.version === npm['dist-tags'].latest) : null;
const day = (iso) => (iso ? iso.slice(0, 10) : null);

// ---------- Storybook ----------

const sbIndex = await getJson(`${cfg.storybookUrl}/index.json`);
if (!sbIndex) die(`${cfg.storybookUrl}/index.json not found`);
const sbEntries = Object.values(sbIndex.entries || {});

// ---------- tokens: build them at SHA ----------

const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'hz-docs-'));
let light, dark, tokenGroups;
try {
	execFileSync('sh', ['-c', `git -C "$0" archive "$1" | tar -x -C "$2"`, TOP, SHA, tmp]);
	fs.symlinkSync(path.join(ROOT, 'node_modules'), path.join(tmp, 'node_modules'));
	execFileSync('node', ['build-tokens.js'], { cwd: tmp, stdio: 'pipe' });
	const parseCss = (file) => {
		const map = new Map();
		for (const line of fs.readFileSync(file, 'utf8').split('\n')) {
			const m = line.match(/^\s*(--[\w-]+):\s*(.*?);/);
			if (m) map.set(m[1], m[2]);
		}
		return map;
	};
	light = parseCss(path.join(tmp, 'build/css/tokens.css'));
	dark = parseCss(path.join(tmp, 'build/css/tokens-dark.css'));
	const strip = (css) => css.replace(/ *\/\*\*[\s\S]*?\*\//g, '');
	fs.mkdirSync(path.join(ROOT, 'src/styles'), { recursive: true });
	fs.writeFileSync(
		path.join(ROOT, 'src/styles/horizon-tokens.css'),
		`/* Generated by docs-site/scripts/generate.mjs: the Horizon token build (build-tokens.js) at ${SHA}. Don't edit by hand. */\n` +
			strip(fs.readFileSync(path.join(tmp, 'build/css/tokens.css'), 'utf8')) +
			'\n' +
			strip(fs.readFileSync(path.join(tmp, 'build/css/tokens-dark.css'), 'utf8')),
	);
	// Which source file each token comes from.
	const { default: StyleDictionary } = await import('style-dictionary');
	const files = {
		'Core scale': 'tokens/core.value.tokens.json',
		Semantic: 'tokens/semantic.light.tokens.json',
		Typography: 'tokens/typography.web.tokens.json',
		'Typography styles': 'tokens/typography.styles.tokens.json',
		Effects: 'tokens/effects.styles.tokens.json',
	};
	tokenGroups = new Map();
	for (const [group, f] of Object.entries(files)) {
		if (!fs.existsSync(path.join(tmp, f))) continue;
		const sd = new StyleDictionary({
			source: [path.join(tmp, f)],
			include: Object.values(files)
				.filter((x) => x !== f && fs.existsSync(path.join(tmp, x)))
				.map((x) => path.join(tmp, x)),
			platforms: { css: { transformGroup: 'css' } },
			log: { verbosity: 'silent', warnings: 'disabled' },
		});
		const { allTokens } = await sd.getPlatformTokens('css');
		for (const tok of allTokens) if (tok.isSource) tokenGroups.set(`--${tok.name}`, group);
	}
} finally {
	fs.rmSync(tmp, { recursive: true, force: true });
}
const darkValue = (name) => (dark.has(name) ? c(dark.get(name)) : 'same as light');

// ---------- components that get a page ----------

const paged = board.components.filter(
	(r) => ['Completed', 'Released'].includes(r.development) && r.releaseVerdict === 'Cleared',
);
const slugOf = (name) => name.toLowerCase();

function parseComponent(row) {
	const name = row.name;
	const dir = `src/components/${name}`;
	for (const f of [`${name}.tsx`, `${name}.css`, `${name}.stories.tsx`])
		if (!has(`${dir}/${f}`)) die(`${dir}/${f} doesn't exist at ${SHORT}, but ${name} is Cleared on the board.`);
	const tsx = show(`${dir}/${name}.tsx`);
	const css = show(`${dir}/${name}.css`);
	const stories = show(`${dir}/${name}.stories.tsx`);
	const intentPath = `${dir}/${name}.intent.json`;
	const intent = has(intentPath) ? JSON.parse(show(intentPath)) : null;
	const tsxLines = tsx.split('\n');
	const lineOf = (re, from = 0) => {
		for (let i = from; i < tsxLines.length; i++) if (re.test(tsxLines[i])) return i + 1;
		return null;
	};

	// Union types.
	const unions = [];
	for (const m of tsx.matchAll(/export type (\w+)\s*=\s*([^;]+);/g)) {
		const values = [...m[2].matchAll(/"([^"]+)"/g)].map((x) => x[1]);
		unions.push({ name: m[1], values, line: lineOf(new RegExp(`export type ${m[1]}\\b`)) });
	}

	// Props interface, with doc comments.
	const im = tsx.match(new RegExp(`export interface (${name}Props)\\s*(?:extends\\s+([^{]+))?\\{([\\s\\S]*?)\\n\\}`));
	const props = [];
	let propsExtends = null;
	let propsLine = null;
	if (im) {
		propsExtends = im[2]?.trim() || null;
		propsLine = lineOf(new RegExp(`export interface ${im[1]}\\b`));
		let doc = null;
		const bodyLines = im[3].split('\n');
		let inDoc = false;
		let buf = [];
		for (const raw of bodyLines) {
			const l = raw.trim();
			if (l.startsWith('/**')) {
				inDoc = true;
				buf = [];
			}
			if (inDoc) {
				buf.push(l.replace(/^\/\*\*|\*\/$|^\*/g, '').trim());
				if (l.endsWith('*/')) {
					inDoc = false;
					doc = buf.filter(Boolean).join(' ');
				}
				continue;
			}
			const pm = l.match(/^(\w+)(\?)?:\s*([^;]+);/);
			if (pm) {
				props.push({ name: pm[1], optional: !!pm[2], type: pm[3].trim(), doc, line: lineOf(new RegExp(`^\\s*${pm[1]}\\??:`), propsLine) });
				doc = null;
			}
		}
	}
	// Defaults from the destructured signature.
	const sig = tsx.match(new RegExp(`export function ${name}\\(\\{([\\s\\S]*?)\\}\\s*:`));
	const defaults = {};
	if (sig) for (const m of sig[1].matchAll(/(\w+)\s*=\s*([^,\n]+)/g)) defaults[m[1]] = m[2].trim();
	for (const p of props) p.default = defaults[p.name] ?? null;

	// CSS: declarations with line numbers, and every token read.
	const cssLines = css.split('\n');
	const tokensRead = [...new Set([...css.matchAll(/var\((--[\w-]+)/g)].map((m) => m[1]))].sort();
	function findDecl(selector, property) {
		let current = null;
		for (let i = 0; i < cssLines.length; i++) {
			const l = cssLines[i];
			const open = l.match(/^([^{]+)\{/);
			if (open) current = open[1];
			const sels = (current ?? '').split(',').map((s) => s.trim());
			// A rule may start on an earlier line (comma-separated selector list).
			if (!open && /,\s*$/.test(l)) current = null;
			if (current && sels.includes(selector)) {
				const d = l.match(new RegExp(`^\\s*${property}:\\s*([^;]+);`));
				if (d) return { line: i + 1, text: l.trim() };
			}
			if (l.includes('}')) current = null;
		}
		return null;
	}

	// Stories: which are variant-matrix rows, which are examples.
	const unionProp = props.find((p) => unions.some((u) => u.name === p.type));
	const storyDefs = [];
	const exportRe = /export const (\w+)\s*:\s*Story\s*=\s*\{/g;
	const starts = [...stories.matchAll(exportRe)];
	starts.forEach((m, i) => {
		const body = stories.slice(m.index, starts[i + 1]?.index ?? stories.length);
		const line = stories.slice(0, m.index).split('\n').length;
		const argVal = unionProp ? body.match(new RegExp(`${unionProp.name}:\\s*"([^"]+)"`)) : null;
		const isRow = !/render\s*:/.test(body) && !!argVal;
		storyDefs.push({ exportName: m[1], line, isRow, value: argVal?.[1] ?? null, body });
	});
	const sbFor = sbEntries.filter((e) => e.importPath?.includes(`/${name}/${name}.stories`));
	for (const s of storyDefs) s.sb = sbFor.find((e) => e.exportName === s.exportName && e.type === 'story') ?? null;
	const sbDocs = sbFor.find((e) => e.type === 'docs') ?? null;

	// Git history of the component folder.
	const log = git('log', '--format=%H%x09%h%x09%ad%x09%s', '--date=short', SHA, '--', dir)
		.split('\n')
		.filter(Boolean)
		.map((l) => {
			const [hash, short, date, subject] = l.split('\t');
			return { hash, short, date, subject, version: versionOf(hash) };
		});
	const since = tags.find((tag) => has('src/index.ts', tag) && new RegExp(`export \\{[^}]*\\b${name}\\b`).test(show('src/index.ts', tag)));

	return { row, name, dir, tsx, css, intent, intentPath, unions, props, propsExtends, propsLine, tokensRead, findDecl, storyDefs, sbDocs, log, since: since?.replace(/^v/, '') ?? null, unionProp };
}

const comps = paged.map(parseComponent);

// ---------- release review facts (for News and the Design tab) ----------

function reviewFacts(url) {
	const m = url?.match(/github\.com\/[^/]+\/[^/]+\/blob\/([0-9a-f]{40})\/(.+)$/);
	if (!m) return null;
	try {
		const md = show(m[2], m[1]);
		return {
			url,
			date: md.match(/\*\*Date:\*\*\s*(\d{4}-\d{2}-\d{2})/)?.[1] ?? null,
			verdict: md.match(/\*\*Verdict:\*\*\s*\*\*(\w+)\*\*/)?.[1] ?? null,
			sha: md.match(/\*\*Reviewed SHA:\*\*\s*`([0-9a-f]+)`/)?.[1] ?? null,
			warnings: (mdSection(md, '## Warnings (not blocking)') ?? '')
				.split('\n')
				.filter((l) => l.startsWith('- '))
				.map((l) => l.slice(2)),
		};
	} catch {
		return { url, date: null, verdict: null, sha: null, warnings: [] };
	}
}

// Rulings in decisions.md that name the component in their heading.
function rulingsFor(name) {
	if (!decisions) return [];
	const out = [];
	for (const m of decisions.matchAll(/^## (.+)$/gm)) {
		if (!new RegExp(`\\b${name}\\b`).test(m[1])) continue;
		const body = mdSection(decisions, `## ${m[1]}`);
		const rulingPara = body.match(/\*\*Ruling\.\*\*\s*([\s\S]*?)(?=\n\*\*[A-Z][^*]*\.\*\*|$)/)?.[1] ?? '';
		const sentence = rulingPara.split('\n')[0].trim().replace(/:$/, '.');
		const tableRows = rulingPara
			.split('\n')
			.filter((l) => /^\|/.test(l) && !/^\|\s*-/.test(l))
			.map((l) => l.split('|').slice(1, -1).map((x) => x.trim()));
		// Columns are found by their header, so a table with or without a Selector column reads right.
		const head = (tableRows[0] ?? []).map((h) => h.toLowerCase());
		const col = (n) => head.indexOf(n);
		const values = tableRows.slice(1).map((r) => ({ cells: r, value: r[col('value')] ?? r[0], property: r[col('property')] ?? r[1], selector: col('selector') >= 0 ? r[col('selector')] : null, lines: r[col('lines')] ?? r[2] }));
		out.push({ title: m[1], ruling: sentence || null, values, notRuled: body.match(/\*\*Not ruled\.\*\*\s*([^\n]+)/)?.[1] ?? null });
	}
	return out;
}

// Markdown link text inside a table cell: strip backticks/emphasis the source used.
const plain = (s) => s.replace(/`/g, '').replace(/\*\*/g, '');

// ---------- component page ----------

// Presentation-only, explicit per-component omissions of Usage-tab sections, at the
// user's request. Nothing else is affected: any component not listed keeps every section,
// and sources of truth (intent files, figma.json) are not touched.
const OMIT_USAGE_SECTIONS = {
	Avatar: ['Where it goes', 'Composition'],
	Button: ['Where it goes', 'Composition'],
	Checkbox: ['Where it goes', 'Composition'],
};

function componentPage(cp) {
	const { name, row, intent, intentPath } = cp;
	const fig = figma.components?.[name] ?? null;
	const review = reviewFacts(row.releaseReview);
	const status = row.development;
	const storyBase = `${cfg.storybookUrl}/?path=/story/`;
	const firstStory = cp.storyDefs.find((s) => s.sb)?.sb;
	const figmaEmbed = fig ? `https://embed.figma.com/design/${figma.file.key}/${figma.file.name}?node-id=${fig.node.id.replace(':', '-')}&embed-host=horizon-docs` : null;

	const header = [
		'<div class="hz-page-header">',
		`<Badge text="${attr(status)}" variant="${status === 'Released' ? 'success' : 'note'}" />`,
		cp.since ? `<span>Shipped in ${t(cp.since)}</span>` : `<span>Not in a published version yet</span>`,
		'<span class="hz-page-header__links">',
		firstStory ? `<a href="${attr(storyBase + firstStory.id)}">Storybook</a>` : '',
		row.figma ? `<a href="${attr(row.figma)}">Figma node ${t(fig?.node.id ?? '')}</a>` : '',
		`<a href="${attr(tree(cp.dir))}">Source</a>`,
		'</span>',
		'</div>',
	]
		.filter(Boolean)
		.join('\n');

	const unreleased = cp.log.filter((l) => !l.version);
	const sinceNote =
		cp.since && unreleased.length
			? `\n\nThis page documents ${name} at ${c(SHORT)}. ${unreleased.length} commit${unreleased.length > 1 ? 's' : ''} to ${c(cp.dir)} since ${t(cp.since)} ${unreleased.length > 1 ? "aren't" : "isn't"} in a published version yet; the Changelog tab lists ${unreleased.length > 1 ? 'them' : 'it'}.`
			: '';

	// ----- Usage -----
	const usage = [];
	const omit = new Set(OMIT_USAGE_SECTIONS[name] ?? []);
	usage.push('## When to use it');
	if (!intent) usage.push(notice(`No ${intentPath} at ${SHORT}.`));
	else if (!intent.use_when?.length) usage.push(notice(`No usage region in Figma for ${name} (use_when is empty in ${intentPath}).`));
	else usage.push(intent.use_when.map((x) => `- ${t(x)}`).join('\n'));

	if (!omit.has('Where it goes')) {
		usage.push('## Where it goes');
		if (intent?.placement?.length) usage.push(intent.placement.map((x) => `- ${t(x)}`).join('\n'));
		else usage.push(notice(`The stories show ${name} on its own, so there's no placement to show (placement is empty in ${intentPath}).`));
	}

	usage.push('## When not to use it');
	if (!intent?.dont_use_when?.length) usage.push(notice(`No "when not to use" items for ${name} (dont_use_when is empty in ${intentPath}).`));
	else
		usage.push(
			intent.dont_use_when
				.map((x) => `- ${t(x.when)}<br/>${x.instead ? `**Instead:** ${t(x.instead)}` : '*The Figma page names no alternative.*'}`)
				.join('\n'),
		);

	usage.push('## Best practice');
	if (fig?.usage?.best_practice?.length)
		usage.push(
			`From the Figma documentation page (usage node ${c(fig.usage.node)}), as written. These items aren't carried into ${c(`${name}.intent.json`)}, which has no field for them.\n\n` +
				fig.usage.best_practice.map((x) => `- ${t(x)}`).join('\n'),
		);
	else usage.push(notice(`No best-practice items for ${name} in sources/figma.json (no usage region was read), and ${name}.intent.json has no field for them.`));

	usage.push('## What each variant is for');
	if (!intent?.variant_intent) usage.push(notice(`No variant_intent in ${intentPath}.`));
	else {
		const prop = cp.unionProp?.name ?? fig?.variantMatrix?.properties?.[0]?.name ?? 'variant';
		usage.push(
			'| Property | Value | What it is for |\n|---|---|---|\n' +
				Object.entries(intent.variant_intent)
					.map(([k, v]) => `| ${c(prop)} | ${c(k)} | ${v ? t(v) : '*Figma doesn\'t say.*'} |`)
					.join('\n'),
		);
	}

	usage.push('## Accessibility');
	if (!intent?.a11y?.length) usage.push(notice(`No accessibility facts in ${intentPath}.`));
	else
		usage.push(
			intent.a11y
				.map((a) => {
					const [file, line] = a.source.split(':');
					return `- ${t(a.fact)} [${c(a.source)}](${blob(file, line)})`;
				})
				.join('\n'),
		);

	if (!omit.has('Composition')) {
		usage.push('## Composition');
		if (intent?.pairs_with?.length) usage.push(`The stories compose ${name} with: ${intent.pairs_with.map((x) => t(x)).join(', ')}.`);
		else usage.push(notice(`The stories compose ${name} with no other Horizon component (pairs_with is empty in ${intentPath}).`));
	}

	usage.push('## What this version promises');
	const promiseHeading = `## What ${pkg.version} commits you to`;
	const promise = mdSection(versioning, promiseHeading);
	if (promise) usage.push(`From [Versioning](/get-started/versioning/) (${c('VERSIONING.md')} at ${c(SHORT)}):\n\n> ${t(plain(promise)).replace(/\n/g, '\n> ')}`);
	else usage.push(notice(`VERSIONING.md at ${SHORT} has no "${promiseHeading.slice(3)}" section.`));

	// ----- Examples -----
	const examples = [];
	examples.push('## From the README');
	const use = readmeSection('Use');
	if (use) {
		const code = use.match(/```(\w+)?\n([\s\S]*?)```/);
		if (!code) examples.push(notice('The README has a Use section but no code block.'));
		else if (!new RegExp(`<${name}[\\s/>]`).test(code[2])) examples.push(notice(`The README's usage example doesn't use ${name}, so there's no README example for it.`));
		else examples.push('```' + (code[1] ?? '') + ' title="README.md"\n' + code[2] + '```');
	} else examples.push(notice('The README has no usage example.'));

	examples.push('## Stories');
	const exampleStories = cp.storyDefs.filter((s) => !s.isRow);
	if (!exampleStories.length) examples.push(notice(`Every ${name} story is a variant-matrix row; they're linked from the Design tab.`));
	for (const s of exampleStories) {
		examples.push(`### ${t(s.sb?.name ?? s.exportName)}`);
		if (!s.sb) {
			examples.push(notice(`The deployed Storybook's index.json has no entry for ${s.exportName}.`));
			continue;
		}
		examples.push(
			`<StoryFrame title="${attr(`${name} · ${s.sb.name} (light)`)}" src="${attr(`${cfg.storybookUrl}/iframe.html?id=${s.sb.id}&viewMode=story`)}" href="${attr(storyBase + s.sb.id)}" />`,
		);
		examples.push(notice("The Storybook has no theme switch, so there's no dark rendering of this story to embed."));
	}
	if (cp.storyDefs.some((s) => s.isRow))
		examples.push(`The single-variant stories (${cp.storyDefs.filter((s) => s.isRow).map((s) => c(s.exportName)).join(', ')}) are rows of the variant matrix; the Design tab links each one.`);

	// ----- Code -----
	const code = [];
	code.push('## Import');
	const typeExports = [...indexTs.matchAll(/export type \{([^}]+)\}/g)].flatMap((m) => m[1].split(',').map((x) => x.trim())).filter((x) => x.startsWith(name));
	code.push('```tsx\n' + `import { ${name} } from "${pkg.name}";\n` + (typeExports.length ? `import type { ${typeExports.join(', ')} } from "${pkg.name}";\n` : '') + '```');
	code.push(`${c(pkg.name + '/tokens.css')} and ${c(pkg.name + '/styles.css')} must be loaded too; see [Developing](/developing/introduction/).`);

	code.push('## Props');
	if (!cp.props.length) code.push(notice(`No ${name}Props interface found in ${name}.tsx.`));
	else {
		code.push(
			'| Prop | Type | Default | Description |\n|---|---|---|---|\n' +
				cp.props
					.map((p) => `| [${c(p.name)}](${blob(`${cp.dir}/${name}.tsx`, p.line)}) | ${c(p.type)} | ${p.default ? c(p.default) : '—'} | ${p.doc ? t(p.doc) : '—'} |`)
					.join('\n'),
		);
		if (cp.props.every((p) => !p.doc)) code.push(notice(`${name}.tsx has no doc comments on its props, so there are no descriptions to show.`));
		if (cp.propsExtends) code.push(`${c(name + 'Props')} also extends ${c(cp.propsExtends)}, so native attributes pass through to the element ([${c(`${name}.tsx:${cp.propsLine}`)}](${blob(`${cp.dir}/${name}.tsx`, cp.propsLine)})).`);
	}

	code.push('## Union types');
	if (!cp.unions.length) code.push(notice(`${name}.tsx exports no union types.`));
	for (const u of cp.unions) code.push(`[${c(u.name)}](${blob(`${cp.dir}/${name}.tsx`, u.line)}): ${u.values.map(c).join(', ')}`);

	code.push('## Tokens it needs');
	code.push(
		`Every CSS custom property ${c(`${name}.css`)} reads, with its value in the token build at ${c(SHORT)}.\n\n| Token | Light | Dark |\n|---|---|---|\n` +
			cp.tokensRead.map((n) => `| ${c(n)} | ${light.has(n) ? c(light.get(n)) : '**not defined**'} | ${darkValue(n)} |`).join('\n'),
	);
	if (intent?.required_tokens) {
		const a = JSON.stringify(intent.required_tokens);
		const b = JSON.stringify(cp.tokensRead);
		code.push(a === b ? `This matches ${c('required_tokens')} in ${c(`${name}.intent.json`)} exactly.` : notice(`required_tokens in ${name}.intent.json doesn't match the tokens ${name}.css reads.`));
	}

	code.push('## Storybook props table');
	if (cp.sbDocs) code.push(`<StoryFrame title="${attr(`${name} docs`)}" src="${attr(`${cfg.storybookUrl}/iframe.html?id=${cp.sbDocs.id}&viewMode=docs`)}" href="${attr(`${cfg.storybookUrl}/?path=/docs/${cp.sbDocs.id}`)}" />`);
	else code.push(notice(`The deployed Storybook publishes no docs (autodocs) page for ${name}, so there's no props table to embed.`));

	// ----- Design -----
	const design = [];
	design.push('## Figma node');
	if (!fig) design.push(notice(`No Figma read for ${name} in sources/figma.json.`));
	else {
		design.push(`<FigmaFrame title="${attr(`${name} · Figma node ${fig.node.id}`)}" src="${attr(figmaEmbed)}" href="${attr(row.figma)}" />`);
		design.push(`${fig.page ? `Page ${c(fig.page.name)} (${c(fig.page.id)}), ${fig.component ? `documentation frame ${c(fig.node.name)} (${c(fig.node.id)}), component set ${c(fig.component.name)} (${c(fig.component.id)})` : `component set ${c(fig.node.name)} (${c(fig.node.id)})`}` : `Documentation frame ${c(fig.node.name)} (${c(fig.node.id)})${fig.component ? `, component ${c(fig.component.name)} (${c(fig.component.id)})` : ''}; the page it sits on wasn't identified in the Figma read`}. The file is shared with the team only, so the frame and the link ask anyone outside it to sign in.`);
		if (fig.figlog) design.push(`The page's FigLog status reads **${t(fig.figlog.status)}**.`);
	}

	design.push('## Variant matrix');
	if (fig?.variantMatrix) {
		const props = fig.variantMatrix.properties;
		design.push(`${props.map((p) => `${c(p.name)} (${p.values.length})`).join(' × ')} = ${fig.variantMatrix.cells} cells. ${t(fig.variantMatrix.note)}`);
		const main = props.find((p) => p.name === cp.unionProp?.name) ?? props[0];
		design.push(
			`| ${c(main.name)} | Figma node | Story |\n|---|---|---|\n` +
				main.values
					.map((v) => {
						// A component with no union type has no story arg to match on: match the story named after the value.
						const s = cp.storyDefs.find((x) => x.isRow && x.value === v.value) ?? (cp.unionProp ? null : cp.storyDefs.find((x) => x.exportName.toLowerCase() === v.value.toLowerCase()));
						return `| ${c(v.value)} | ${v.node ? c(v.node) : '—'} | ${s?.sb ? `[${t(s.sb.name)}](${storyBase + s.sb.id})` : '*no story*'} |`;
					})
					.join('\n'),
		);
		for (const p of props.filter((x) => x !== main)) {
			const codeProp = cp.props.find((x) => x.name.toLowerCase() === p.name.toLowerCase());
			const argsDefault = codeProp?.default;
			// Stories whose args set this prop (matched to the code prop case-insensitively).
			const setting = codeProp ? cp.storyDefs.filter((x) => x.sb && new RegExp(`\\b${codeProp.name}:`).test(x.body.slice(0, x.body.search(/render\s*:/) < 0 ? undefined : x.body.search(/render\s*:/)))) : [];
			design.push(
				setting.length
					? `${c(p.name)}: ${p.values.map((v) => c(v.value)).join(', ')}. Stories that set ${c(codeProp.name)}: ${setting.map((x) => `[${t(x.sb.name)}](${storyBase + x.sb.id})`).join(', ')}${argsDefault ? `; it defaults to ${c(argsDefault)}` : ''}.`
					: `${c(p.name)}: ${p.values.map((v) => c(v.value)).join(', ')}. No story sets ${c(p.name)} on its own${argsDefault ? `; it defaults to ${c(argsDefault)} and can be switched with the Storybook controls` : ''}.`,
			);
		}
	} else design.push(notice(`No variant matrix for ${name} in sources/figma.json.`));

	design.push('## Themes');
	design.push(fig?.themes ? t(fig.themes.note) : notice(`No theme information for ${name} in sources/figma.json.`));
	design.push(`The token build defines ${light.size} tokens for light and redeclares ${dark.size} for dark; the Code tab shows ${name}'s tokens in both.`);
	design.push(notice("The Storybook has no theme switch, so there's no dark rendering of the stories to show."));

	design.push('## Values Figma never bound');
	if (fig?.unboundValues?.length) {
		design.push(
			`Values on the Figma node that aren't bound to a variable, and what ${c(`${name}.css`)} at ${c(SHORT)} does with each.\n\n| Layer | Property | Figma value | In the code |\n|---|---|---|---|\n` +
				fig.unboundValues
					.map((u) => {
						const d = cp.findDecl(u.css.selector, u.css.property);
						const inCode = d ? `[${c(d.text)}](${blob(`${cp.dir}/${name}.css`, d.line)})` : `No ${c(u.css.property)} on ${c(u.css.selector)}`;
						return `| ${t(u.layer)} | ${t(u.property)} | ${c(u.value)} | ${inCode} |`;
					})
					.join('\n'),
		);
	} else design.push(notice(`No unbound-value read for ${name} in sources/figma.json.`));

	design.push('## Figma variables against the token build');
	if (fig?.boundVariables) {
		const rows = Object.entries(fig.boundVariables).map(([v, figVal]) => {
			const codeName = v.toLowerCase();
			const built = light.get(codeName);
			const same = built && (built.toLowerCase() === String(figVal).toLowerCase() || built === `${figVal}px`);
			return { v, figVal, codeName, built, same };
		});
		design.push(
			'| Figma variable | Figma value | Token in the build | Built light value | Agrees |\n|---|---|---|---|---|\n' +
				rows.map((r) => `| ${c(r.v)} | ${c(r.figVal)} | ${r.built ? c(r.codeName) : '*no such token*'} | ${r.built ? c(r.built) : '—'} | ${!r.built ? '**no token**' : r.same ? 'yes' : '**no**'} |`).join('\n'),
		);
		const diff = rows.filter((r) => r.built && !r.same && /^#/.test(r.figVal));
		const missing = rows.filter((r) => !r.built);
		if (missing.length) design.push(`${missing.map((r) => c(r.v)).join(', ')} ${missing.length > 1 ? 'are' : 'is'} bound in Figma but the token build has no token of that name.`);
		const diffRead = diff.filter((r) => cp.tokensRead.includes(r.codeName));
		const diffUnread = diff.filter((r) => !cp.tokensRead.includes(r.codeName));
		if (diffRead.length) design.push(`${diffRead.length} colour variable${diffRead.length > 1 ? 's' : ''} in Figma still hold${diffRead.length > 1 ? '' : 's'} a different value from the token build, so the design file and the shipped component render ${diffRead.map((r) => c(r.v)).join(', ')} differently.`);
		if (diffUnread.length) design.push(`${diffUnread.map((r) => c(r.v)).join(', ')} ${diffUnread.length > 1 ? 'hold' : 'holds'} a different value in Figma from the token of the same name in the build, but ${c(`${name}.css`)} doesn't read ${diffUnread.length > 1 ? 'those tokens' : 'that token'}, so this doesn't change how the shipped component renders.`);
	}

	design.push('## Design gaps recorded against it');
	const gaps = [];
	for (const r of rulingsFor(name))
		gaps.push(
			`- **${t(r.title)}** ([decisions.md](${blob('decisions.md')})). ${r.ruling ? t(plain(r.ruling)) : ''}` +
				(r.values.length ? ` Accepted values: ${r.values.map((v) => `${c(plain(v.value))} (${t(plain(v.property))}${v.selector ? `, ${c(plain(v.selector))}` : ''}, line${/,/.test(v.lines) ? 's' : ''} ${t(v.lines)})`).join('; ')}.` : '') +
				(r.notRuled ? ` *Not ruled:* ${t(plain(r.notRuled))}` : ''),
		);
	for (const w of review?.warnings ?? []) gaps.push(`- From the [release review](${review.url}): ${t(plain(w))}`);
	design.push(gaps.length ? gaps.join('\n') : notice(`No design gaps are recorded against ${name} in decisions.md or its release review.`));

	// ----- Changelog -----
	const changelog = [];
	changelog.push(`Every commit to ${c(cp.dir)} up to ${c(SHORT)}, newest first, with the published version that carries it.`);
	changelog.push(
		'| Commit | Date | Version | Change |\n|---|---|---|---|\n' +
			cp.log.map((l) => `| [${c(l.short)}](${commitUrl(l.hash)}) | ${l.date} | ${l.version ? t(l.version) : '*Unreleased*'} | ${t(l.subject)} |`).join('\n'),
	);

	const tab = (label, body) => `<TabItem label="${label}">\n\n${body.join('\n\n')}\n\n</TabItem>`;
	return [
		frontmatter({ title: name, description: `${name}: when to use it, how to call it, what it was built from, and what has changed.` }),
		'',
		"import { Badge, Tabs, TabItem } from '@astrojs/starlight/components';",
		"import StoryFrame from '../../../../components/StoryFrame.astro';",
		"import FigmaFrame from '../../../../components/FigmaFrame.astro';",
		'',
		GEN,
		'',
		header,
		sinceNote,
		'',
		'<Tabs>',
		tab('Usage', usage),
		tab('Examples', examples),
		tab('Code', code),
		tab('Design', design),
		tab('Changelog', changelog),
		'</Tabs>',
	].join('\n');
}

for (const cp of comps) write(`core/components/${slugOf(cp.name)}.mdx`, componentPage(cp));

// ---------- All components ----------

{
	const rows = comps.map((cp) => `| [${cp.name}](/core/components/${slugOf(cp.name)}/) | ${t(cp.row.development)} | ${cp.since ? t(cp.since) : '—'} | ${cp.intent?.use_when?.[0] ? t(cp.intent.use_when[0]) : '—'} |`);
	const others = board.components.filter((r) => !paged.includes(r));
	write(
		'core/components/overview.mdx',
		[
			frontmatter({ title: 'All components', description: `Every Horizon component with a page on this site.` }),
			'',
			GEN,
			'',
			`${comps.length} component${comps.length === 1 ? '' : 's'} on this site. A component gets a page once the registry reads ${c('Completed')} or ${c('Released')} and its release review is ${c('Cleared')}.`,
			'',
			'| Component | Status | Shipped in | What it is for |\n|---|---|---|---|\n' + rows.join('\n'),
			'',
			'"What it is for" is the first "when to use" item from each component\'s intent file, which is transposed from its Figma documentation page.',
			'',
			'## What is not here',
			'',
			others.length
				? `${others.length} other component${others.length === 1 ? ' is' : 's are'} on the registry without a cleared review. They're listed on the [Roadmap](/get-started/roadmap/).`
				: 'Every component on the registry has a page.',
		].join('\n'),
	);
}

// ---------- Tokens ----------

{
	const usedBy = new Map();
	for (const cp of comps) for (const n of cp.tokensRead) usedBy.set(n, [...(usedBy.get(n) ?? []), cp.name]);
	const link = (n) => `[${n}](/core/components/${slugOf(n)}/)`;
	const groups = new Map();
	for (const n of light.keys()) {
		const g = tokenGroups.get(n) ?? 'Other';
		groups.set(g, [...(groups.get(g) ?? []), n]);
	}
	const table = (names) =>
		'| Token | Light | Dark | Used by |\n|---|---|---|---|\n' +
		names.map((n) => `| ${c(n)} | ${c(light.get(n))} | ${darkValue(n)} | ${(usedBy.get(n) ?? []).map(link).join(', ') || '—'} |`).join('\n');
	const order = ['Semantic', 'Core scale', 'Typography', 'Typography styles', 'Effects', 'Other'];
	const body = [
		frontmatter({ title: 'Tokens', description: 'Every design token the package ships, in light and dark.' }),
		'',
		GEN,
		'',
		`The token build (${c('build-tokens.js')}) at ${c(SHORT)} writes ${light.size} CSS custom properties to ${c('tokens.css')}, shipped as ${c(pkg.name + '/tokens.css')}. ${dark.size} of them are redeclared under ${c('[data-theme="dark"]')}; the rest are the same in both themes.`,
		'',
		'| Group | Tokens | Source file |\n|---|---|---|\n' +
			order.filter((g) => groups.has(g)).map((g) => `| ${g} | ${groups.get(g).length} | ${{ Semantic: c('tokens/semantic.light.tokens.json') + ', ' + c('tokens/semantic.dark.tokens.json'), 'Core scale': c('tokens/core.value.tokens.json'), Typography: c('tokens/typography.web.tokens.json'), 'Typography styles': c('tokens/typography.styles.tokens.json'), Effects: c('tokens/effects.styles.tokens.json'), Other: '—' }[g]} |`).join('\n'),
		'',
		'## What the components on this site depend on',
		'',
		usedBy.size ? table([...usedBy.keys()].sort()) : notice('No component on this site reads a token.'),
	];
	for (const g of order.filter((x) => groups.has(x))) body.push('', `## ${g}`, '', table(groups.get(g)));
	write('core/tokens.mdx', body.join('\n'));
}

// ---------- Changelog ----------

{
	const body = [frontmatter({ title: 'Changelog', description: `What each version of ${pkg.name} contains.` }), '', GEN, ''];
	const lastTag = tags.at(-1);
	const unreleased = lastTag
		? git('log', '--format=%H%x09%h%x09%ad%x09%s', '--date=short', `${lastTag}..${SHA}`, '--', 'src', 'package.json').split('\n').filter(Boolean)
		: [];
	body.push('## Unreleased', '');
	if (!lastTag) body.push(`No version is tagged at or before ${c(SHORT)}.`);
	else if (!unreleased.length) body.push(`Nothing: no commit to ${c('src/')} or ${c('package.json')} between ${c(lastTag)} and ${c(SHORT)}.`);
	else {
		body.push(`Commits to ${c('src/')} or ${c('package.json')} between ${c(lastTag)} and ${c(SHORT)}, not in a published version yet:`, '');
		for (const l of unreleased) {
			const [hash, short, date, subject] = l.split('\t');
			const files = git('show', '--name-only', '--format=', hash).split('\n').filter((f) => f.startsWith('src/') || f === 'package.json');
			body.push(`- [${c(short)}](${commitUrl(hash)}) ${date}: ${t(subject)} (${files.map(c).join(', ')})`);
		}
	}
	for (const tag of [...tags].reverse()) {
		const v = tag.replace(/^v/, '');
		const pub = published.find((p) => p.version === v);
		body.push('', `## ${v}${pub ? ` — ${day(pub.time)}` : ''}`, '');
		body.push(pub ? `Published to npm as ${c(`${pkg.name}@${v}`)}, tag ${c(tag)}.` : `Tagged ${c(tag)}. Not found on npm.`);
		const tagPkg = JSON.parse(show('package.json', tag));
		const tagIndex = show('src/index.ts', tag);
		const compsAt = [...tagIndex.matchAll(/export \{([^}]+)\}/g)].flatMap((m) => m[1].split(',').map((x) => x.trim()));
		const typesAt = [...tagIndex.matchAll(/export type \{([^}]+)\}/g)].flatMap((m) => m[1].split(',').map((x) => x.trim()));
		body.push('', '### Contents', '');
		body.push(`- Components: ${compsAt.map((n) => (comps.some((cp) => cp.name === n) ? `[${n}](/core/components/${slugOf(n)}/)` : c(n))).join(', ') || 'none'}`);
		if (typesAt.length) body.push(`- Types: ${typesAt.map(c).join(', ')}`);
		const css = Object.keys(tagPkg.exports ?? {}).filter((k) => k.endsWith('.css'));
		if (css.length) body.push(`- Stylesheets: ${css.map((k) => c(k.replace('./', ''))).join(' and ')}`);
		if (tagPkg.peerDependencies) {
			body.push('', '### Requires', '');
			for (const [k, r] of Object.entries(tagPkg.peerDependencies)) body.push(`- ${c(k)} ${c(r)}`);
		}
	}
	write('get-started/changelog.mdx', body.join('\n'));
}

// ---------- Roadmap ----------

{
	const others = board.components.filter((r) => !paged.includes(r));
	const byStatus = new Map();
	for (const r of others) byStatus.set(r.development || '(empty)', [...(byStatus.get(r.development || '(empty)') ?? []), r]);
	const body = [
		frontmatter({ title: 'Roadmap', description: 'What the registry and the recorded design gaps say is open.' }),
		'',
		GEN,
		'',
		"This page lists what the registry and the recorded design gaps say is open. It carries no dates, owners or priorities, because none of those sources states one.",
		'',
		'## Components without a page yet',
		'',
	];
	if (!others.length) body.push('None: every component on the registry has a page.');
	for (const [status, rows] of byStatus) {
		body.push(`### ${t(status)}`, '', '| Component | Category | Design |\n|---|---|---|\n' + rows.map((r) => `| ${t(r.name)} | ${t(r.category || '—')} | ${t(r.design || '—')} |`).join('\n'), '');
	}
	body.push(`Read from the registry on ${t(board.readAt)}.`, '', '## Open design gaps', '');
	let any = false;
	for (const cp of comps) {
		const review = reviewFacts(cp.row.releaseReview);
		const items = [
			...rulingsFor(cp.name).map((r) => `- **${t(r.title)}**: accepted in [decisions.md](${blob('decisions.md')}) until the designer adds matching tokens; still open.`),
			...(review?.warnings ?? []).map((w) => `- ${t(plain(w))} ([release review](${review.url}))`),
		];
		const fig = figma.components?.[cp.name];
		if (fig?.boundVariables) {
			const drift = Object.entries(fig.boundVariables).filter(([v, val]) => /^#/.test(val) && light.get(v.toLowerCase()) && light.get(v.toLowerCase()).toLowerCase() !== val.toLowerCase());
			if (drift.length) items.push(`- ${drift.length} Figma colour variable${drift.length > 1 ? 's' : ''} on the node hold${drift.length > 1 ? '' : 's'} a different value from the token build (${drift.map(([v]) => c(v)).join(', ')}${drift.every(([v]) => !cp.tokensRead.includes(v.toLowerCase())) ? `; ${c(`${cp.name}.css`)} doesn't read ${drift.length > 1 ? 'them' : 'it'}` : ''}); see the [Design tab](/core/components/${slugOf(cp.name)}/).`);
		}
		if (items.length) {
			any = true;
			body.push(`### ${cp.name}`, '', items.join('\n'), '');
		}
	}
	if (!any) body.push('None recorded.');
	write('get-started/roadmap.mdx', body.join('\n'));
}

// ---------- News ----------

{
	const events = [];
	for (const p of published) events.push({ when: p.time, text: `### ${day(p.time)} — ${p.version} published to npm\n\n${c(`${pkg.name}@${p.version}`)} went public. The [changelog](/get-started/changelog/) lists what it carries.` });
	for (const cp of comps) {
		const r = reviewFacts(cp.row.releaseReview);
		if (r?.verdict === 'Cleared' && r.date) {
			const when = git('show', '-s', '--format=%aI', r.url.match(/blob\/([0-9a-f]{40})/)[1]).trim();
			events.push({ when: new Date(when).toISOString(), text: `### ${r.date} — ${cp.name} cleared the release review\n\n[${cp.name}](/core/components/${slugOf(cp.name)}/) cleared its [release review](${r.url}) at ${c(r.sha?.slice(0, 7) ?? '')}.` });
		}
		if (cp.row.astroLink && cp.row.development === 'Released') events.push({ when: board.readAt, text: `### ${board.readAt} — ${cp.name} released\n\n${cp.name} got a verified page on this site, which moves the registry to ${c('Released')}.` });
	}
	events.sort((a, b) => (a.when < b.when ? 1 : -1));
	write(
		'get-started/news.mdx',
		[
			frontmatter({ title: 'News', description: 'What happened, newest first.' }),
			'',
			GEN,
			'',
			'One entry per event, newest first. A version\'s contents are on the [changelog](/get-started/changelog/); this page records when things happened.',
			'',
			events.length ? events.map((e) => e.text).join('\n\n') : 'Nothing yet.',
		].join('\n'),
	);
}

// ---------- Home ----------

{
	const hero = readmeFirstParagraph();
	const install = readmeSection('Install')?.match(/```\w*\n([\s\S]*?)```/)?.[1].trim();
	const lines = [
		frontmatter({ title: 'Horizon Design System', description: hero ?? 'Horizon Design System', template: 'splash' }),
	];
	// hero block needs nested YAML: write it by hand.
	lines[0] = [
		'---',
		'title: Horizon Design System',
		`description: ${JSON.stringify(hero ?? 'Horizon Design System')}`,
		'template: splash',
		'hero:',
		`  tagline: ${JSON.stringify(hero ?? 'No README.md at this commit, so there is no tagline.')}`,
		'  actions:',
		'    - text: Start designing',
		'      link: /designing/introduction/',
		'      icon: right-arrow',
		'    - text: Start coding',
		'      link: /developing/introduction/',
		'      icon: right-arrow',
		'      variant: secondary',
		'    - text: Open Storybook',
		`      link: ${cfg.storybookUrl}`,
		'      icon: external',
		'      variant: minimal',
		'---',
	].join('\n');
	lines.push('', "import { Card, CardGrid, LinkCard } from '@astrojs/starlight/components';", '', GEN, '');
	if (latest) {
		lines.push(`## Latest release — ${latest.version}`, '');
		lines.push(`Published to npm on ${day(latest.time)}. ${comps.length} component${comps.length === 1 ? '' : 's'} on this site, carried by ${light.size} tokens in a light theme and ${dark.size} dark overrides.`);
		if (install) lines.push('', '```bash', install, '```');
		lines.push('', `<LinkCard title="Read the release notes" description="What ${latest.version} contains and what it needs." href="/get-started/changelog/" />`);
	} else {
		lines.push('## Latest release', '', `No version of ${c(pkg.name)} is on npm yet.`);
	}
	lines.push(
		'',
		'## Where to go',
		'',
		'<CardGrid>',
		'<LinkCard title="Start designing" description="The Figma file and how tokens get from Figma into code." href="/designing/introduction/" />',
		`<LinkCard title="Start coding" description="Install the package, load the two stylesheets, render a component." href="/developing/introduction/" />`,
		`<LinkCard title="Components" description="What each component is for, when not to use it, and how to call it." href="/core/components/overview/" />`,
		`<LinkCard title="Tokens" description="Every token the package ships, in light and dark." href="/core/tokens/" />`,
		'</CardGrid>',
		'',
		'## What this site is',
		'',
		'<CardGrid>',
		'<Card title="Explained here, rendered in Storybook">Storybook renders every story live. This site says when to use each component, and embeds and links the matching stories rather than re-rendering anything.</Card>',
		"<Card title=\"Written from the release's own files\">A component's Usage tab is its intent file, the same file the release review checks. A component gets a page only after it clears that review.</Card>",
		'<Card title="The reference is generated">Components, tokens, the changelog, the roadmap, news and this page come out of <code>docs-site/scripts/generate.mjs</code>, from the code, the token build, the stories, Figma and the registry.</Card>',
		'<Card title="It says what is still open">Every component page lists the values Figma never bound and the design gaps recorded against it, and the roadmap lists every gap still open.</Card>',
		'</CardGrid>',
	);
	write('index.mdx', lines.join('\n'));
}

// ---------- Sidebar: the generated component entries in astro.config.mjs ----------

{
	const file = path.join(ROOT, 'astro.config.mjs');
	const src = fs.readFileSync(file, 'utf8');
	const start = '// <generated:components>';
	const end = '// </generated:components>';
	const i = src.indexOf(start);
	const j = src.indexOf(end);
	if (i < 0 || j < 0) die('astro.config.mjs is missing the generated:components markers.');
	const indent = src.slice(src.lastIndexOf('\n', i) + 1, i);
	const entries = comps.map((cp) => `${indent}{ label: '${cp.name}', slug: 'core/components/${slugOf(cp.name)}' },`).join('\n');
	fs.writeFileSync(file, src.slice(0, i + start.length) + '\n' + entries + '\n' + indent + src.slice(j));
}

console.log(`generate: ${SHA}`);
console.log(`generate: ${comps.length} component page(s): ${comps.map((cp) => cp.name).join(', ') || 'none'}`);
for (const w of written) console.log(`  wrote src/content/docs/${w}`);
console.log('  wrote src/styles/horizon-tokens.css');
console.log('  updated the generated sidebar block in astro.config.mjs');
